# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YHDataModelDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

  # Pods for YHDataModelDemo
   pod 'HQDBDecode' , :git => 'ssh://git@git.solot.co:10022/liuhuanqing/HQDBDecode.git'

end
